Update error formatting and messages.

diff --git a/share/zshctl/functions/args_error_default b/share/zshctl/functions/args_error_default
--- a/share/zshctl/functions/args_error_default
+++ b/share/zshctl/functions/args_error_default
@@ -3,30 +3,24 @@ emulate -L zsh
 typeset func=${1:-} reason=${2:-} flag=${3:-}
 shift 3
 case $reason in
-(complete)
-    if (( ${+functions[complete:${func#execute:}]} )); then
-        printf 'complete:%s %s\n' ${func#execute:} "${(j: :)${(@qq)@}}"
-    else
-        printf 'delegate %s\n' "${(j: :)${(qq)@}}"
-    fi
-    ;;
 (unknown)
-    printf 'unknown argument `%s`.\n' $flag 1>&2
-    exit 1
+    printf 'fatal: invalid argument: unknown argument %s.\n' ${(qqq)flag} 1>&2
+    exit 2
     ;;
 (required)
-    printf '`%s` is a required argument.\n' $flag 1>&2
-    exit 1
+    printf 'fatal: required argument: %s is a required argument.\n' ${(qqq)flag} 1>&2
+    exit 3
     ;;
 (execute)
     if [[ $flag = --help ]]; then
         usage
     else
-        abend 'unknown execute directive on `%s` flag `%s`.' $func $flag
+        printf 'fatal: exception: unknown execute directive on %s flag %s.' ${(qqq)func} ${(qqq)flag}
+        exit 1
     fi
     ;;
 (args)
-    printf 'abend: exception: unknown "args" flag %s' ${(@qqq)flag} 1>&2
+    printf 'fatal: exception: unknown "args" flag %s' ${(@qqq)flag} 1>&2
     exit 1
     ;;
 esac
